<?xml version="1.0"?>
<package format="3">
  <name>tb3_vda5050_bridge</name>
  <version>0.2.1</version>
  <description>VDA5050 bridge for TurtleBot3/Nav2</description>

  <maintainer email="nhat.tranduy1997@gmail.com">maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>diagnostic_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>vda5050_msgs</depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>vda5050_client_adapter</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
