/**:
  ros__parameters:
    adapter_ns: "/tb3_3/vda5050_client_adapter"
    odom_topic: "/tb3_3/odom"
    amcl_pose_topic: "/tb3_3/amcl_pose"
    battery_topic: "/tb3_3/battery_state"
    nav2_action_name: "/tb3_3/navigate_to_pose"     # Absolute Nav2 action name.
    map_id: "tb3_world"
    nav2_frame_id: "map"
    position_covariance_threshold: 1.5
    supported_action_types:
      - "initPosition"
      - "startCharging"
      - "stopCharging"
    simulate_charging: true
    initial_pose_topic: "/tb3_3/initialpose"

    nav2_dispatch_timeout_sec: 120.0
    amcl_pose_timeout_sec: 45.0
    pose_stale_move_tolerance_m: 0.15
    speed_limit_topic: "/tb3_3/speed_limit"
