#ifndef ORDER_HANDLER_HPP
#define ORDER_HANDLER_HPP

#include <optional>
#include <string>
#include <nlohmann/json.hpp>

namespace vda5050_fleet_adapter_full_control::vda5050 {

// A resolved waypoint pose in the map frame identified by a
// build_navigate_order() call's map_id -- NOT a frame attached to the
// robot's body, and NOT RMF's world frame. The caller (Connector) resolves
// x/y/theta before calling in here.
struct RobotPose
{
    double x = 0.0;
    double y = 0.0;
    double theta = 0.0;
};

// Builds a two-node, one-edge VDA5050 'order' message for a point-to-point
// route from base to dest -- the exact shape Vda5050Connector::navigate()
// always sent (base at sequenceId 0, edge at 1, dest at 2). This message
// only names the two nodes and the edge between them; it sets no
// trajectory, so the path the AGV actually drives is up to its own
// navigation stack, not guaranteed to be a straight line.
//
// Preconditions the caller must satisfy (not checked here):
// - base and dest are both expressed in the map identified by map_id.
// - x/y/theta/speed_limit are finite.
// header_id is supplied by the caller, which owns the per-robot header
// counter. order_id must be non-empty and generated by the caller before
// calling -- passing "" would let make_order() silently generate its own
// UUID that the caller never sees, breaking completion tracking
// (state_handler's order_finished() always returns false for an empty
// id). This always builds a brand-new order (orderUpdateId fixed at 0);
// it cannot append nodes to an order already in progress.
nlohmann::json build_navigate_order(
    int header_id, const std::string &order_id,
    const std::string &manufacturer, const std::string &serial,
    const std::string &base_node_id, const RobotPose &base,
    const std::string &dest_node_id, const RobotPose &dest,
    const std::string &map_id,
    std::optional<double> speed_limit = std::nullopt);

}  // namespace vda5050_fleet_adapter_full_control::vda5050

#endif  // ORDER_HANDLER_HPP
